### ISSUE TITLE
Does not start up with VSCode and no vim commands work

### ISSUE THREAD

**Issue by janecakemaster** [VSCodeVim/Vim#3753]
Issue Type: <b>Bug</b>

**Describe the bug**
VSCode usually loads the extension with no problem. However, today i opened up VSCode and vim stopped working. when I try to use the command palette to switch to vim mode, i get `command 'toggleVim' not found`. 

**To Reproduce**

1.  open vs code
2.  try to use vim mode
3. try to use any vim command in the command palette

Extension version: 1.8.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by zombiezen** [comment]
This appears to be a regression in 1.8.0. I am also able to reproduce with VS Code 1.33.1 on Linux, and downgrading the extension to 1.7.1 fixes the issue for me.

(For anyone using this workaround, be sure to set `"extensions.autoUpdate": false` to avoid 1.8.0 coming back.)

**Comment by foxbunny** [comment]
As an FYI, it appears to still be an issue in 1.8.1.

**Comment by zombiezen** [comment]
More details here: I ran the command `Developer: Toogle Developer Tools` and looked at the JavaScript console. I got a stack trace very similar to the one in #3473.

<details><pre>
Error: Cannot find module 'winston-transport'
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
	at Function.Module._load (internal/modules/cjs/loader.js:510:25)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:491:111)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:742)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:488)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/util/logger.js:11:25)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/util/logger.js:84:3)
	at Module.t._initNodeRequire.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:713)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:491:111)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:742)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:488)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/mode/modes.js:3:18)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/mode/modes.js:141:3)
	at Module.t._initNodeRequire.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:713)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:491:111)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:742)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:488)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/common/motion/position.js:6:17)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/common/motion/position.js:1064:3)
	at Module.t._initNodeRequire.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:713)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:491:111)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:742)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:488)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/actions/operator.js:20:20)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/actions/operator.js:1014:3)
	at Module.t._initNodeRequire.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:713)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:491:111)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:742)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:488)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/actions/include-all.js:4:1)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/src/actions/include-all.js:19:3)
	at Module.t._initNodeRequire.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:713)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:491:111)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:742)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at n (/usr/share/code/resources/app/out/vs/loader.js:15:488)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/extension.js:16:1)
	at Object.<anonymous> (/home/rlight2/.vscode/extensions/vscodevim.vim-1.8.2/out/extension.js:393:3)
	at Module.t._initNodeRequire.o._compile (/usr/share/code/resources/app/out/vs/loader.js:15:713)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:491:111)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:742)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:31:381)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:747:60
	at D._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:747:168)
	at D._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:746:6)
	at D.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:742:827)
	at Generator.next (<anonymous>)
	at n (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:621)
	at new Promise (<anonymous>)
	at n (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:398)
	at Object.actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:742:529)
	at p._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:479:561)
	at define._activateExtensions.r.length.Promise.all.s.map.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:479:245)
	at Array.map (<anonymous>)
	at p._activateExtensions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:479:233)
	at p.activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:477:126)
	at D._activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:744:680)
	at D._handleEagerExtensions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:748:717)
	at define._startExtensionHost._readyToStartExtensionHost.wait.then.then (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:752:98)
</pre></details>

I followed these steps (same as detailed on #3473) and was able to resolve the issue:

1. Uninstall the vscodevim extension
2. Reload VSCode
3. Delete the ~/.vscode/extensions/vscodevim-1.8.2 folder
4. Reinstall the vscodevim extension
5. Reload VSCode

**Comment by wmmxk** [comment]
Then how to specify the version of vim when installing the vim extension in VScode?  I searched for "vim" and only saw Vim 1.8.2.

**Comment by Dhineshss** [comment]
Vscodevim stopped working suddenly.  Tried deleting extension folders. nothing works
Version 1.12.0

**Comment by Dhineshss** [comment]
Reinstalled previous version 1.11.3. Now its working....

**Comment by fangyuan** [comment]
> Reinstalled previous version 1.11.3. Now its working....

installed vim v1.12.0 and it did not work, back to v1.11.3, it works, thanks

**Comment by hkujy** [comment]
Reinstalled previous version 1.11.3 works. 
Nothing work for the newest version that I installed 1 hour ago

**Comment by Colopatiron** [comment]
How do you install an older version of the extension?

**Comment by hkujy** [comment]
It works now with old version.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by chy373** [comment]
> How do you install an older version of the extension?

![image](https://user-images.githubusercontent.com/5926064/70419879-5ec13a80-1aa1-11ea-8247-7061e38c4d2e.png)

**Comment by XatMassacrE** [comment]
v1.12.0 not work, reinstall with v1.11.3, works, thank you~

**Comment by sztomi** [comment]
https://github.com/VSCodeVim/Vim/issues/4340

**Comment by hamxabaig** [comment]
Yepp suddenly stopped working when it got auto updated to `v1.12.0`, `v1.11.3` works!

**Comment by gomesalexandre** [comment]
Suddenly stopped working for me as well. `1.11.3` works, `1.12.0` didn't.

**Comment by Rom325** [comment]
Stopped working 1h ago because of v1.12.0, reverted back to v1.11.3

**Comment by nevermyuk** [comment]
Stopped working when updated to v1.12, reverted back to v1.11.3 and its working fine again!

**Comment by donizb** [comment]
I think something is wrong with `v1.12 `
`1.11.3` works

**Comment by ChrisShen93** [comment]
not work for me with v1.40.2

**Comment by wnykuang** [comment]
same here, cannot work on 1.12 but works on 1.11

:(

**Comment by yujincheng08** [comment]
Same here. Reinstalled previous version 1.11.3 works.

**Comment by tomGdow** [comment]
Same story with me: 1.12.1 not working (suddenly), revert to 1.11.3 works fine. Thanks to everyone who pointed this out :-)

**Comment by Dhineshss** [comment]
New version !!!!

**1.12.2**
fixed the startup issue. Time to update the new package..

**Comment by ryfow** [comment]
1.12.4 appears to be broken

**Comment by itriese** [comment]
Same story with me: 1.12.4 not working, switched back to 1.12.3 => works fine.

**Comment by bajatin** [comment]
For me none of the previous versions are working. I deleted the extension folder and I even went back till 1.8.0 but its still not working.
Status bar says --Normal-- but works like usual VSCode.

**Comment by sztomi** [comment]
Consider filing a new issue, I think closed ones rarely get any attention.

**Comment by bradparks** [comment]
I had this same issue, but when I went to the developer console, it told me

```Neovim: configure the path to neovim and restart the editor
onDidChangeNotification @ notificationsAlerts.ts:40```

I went to the extensions settings, and defined the path, which I found from the terminal by running

$ which nvim
/usr/local/bin/nvim

I put it in, restarted VS Code and it worked!

**Comment by ckwillling** [comment]
> I had this same issue, but when I went to the developer console, it told me
> 
> ```
> Neovim: configure the path to neovim and restart the editor
> onDidChangeNotification @ notificationsAlerts.ts:40
> ```
> 
> I went to the extensions settings, and defined the path, which I found from the terminal by running
> 
> ```
> $ which nvim
> /usr/local/bin/nvim
> ```
> 
> I put it in, restarted VS Code and it worked!

it does work for me

**Comment by drewbietron** [comment]
This happened with me on a fresh install of my vscode plugins on a new machine.  It installed `1.20.2` and wasn't working.  I went back to `1.11.3` and everything works as expected.

**Comment by Pulpanj** [comment]
Just for record Vim extension does not work if Overtype extension is also installed. Disabling Overtype extension fixed it.

**Comment by gunterja** [comment]
This extension seemed to be the culprit for me:
Name: Auto Import - ES6, TS, JSX, TSX
Id: NuclleaR.vscode-extension-auto-import
Description: Automatically finds, parses and provides code actions and code completion for all available imports. Works with JavaScript and TypeScript. [Forked]
Version: 1.4.3
Publisher: Sergey Korenuk
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=NuclleaR.vscode-extension-auto-import

**Comment by zirahvi** [comment]
Still a problem on Linux (vscodevim 1.22.2, code 1.66.0). No errors/messages in the developer console, just silently stops working.

Restarting VS Code seems to fix the issue, but the extension eventually tops working again.

**Comment by matart15** [comment]
Happening on v1.24.3 and OSX

**Comment by lime45** [comment]
It was the overtype extension for me as well.
