### ISSUE TITLE
1.17.0 clicking causes cursor to jump when using vim hotkeys

### ISSUE THREAD

**Issue by kalenpw** [VSCodeVim/Vim#5248]
**Describe the bug**
Clicking doesn't always properly update cursor position in conjunction with vim hotkeys

**To Reproduce**

1.  Be typing normal navigating with vim hotkeys
2.  Click somewhere else in editor window
3.  Use vim hotkey to move curor
4.  Cursor jumps to previous position ignoring click

Example: if I am currently editing line 20, click on line 50 and then press j the cursor goes to line 21, instead of 51 as it previously did.

**Expected behavior**
Clicking updates the cursor position in such a way that vim recognizes it

**Screenshots**
I'll try to get a screen recording of it happening and update issue with it

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.0
- VSCode version: 1.49.2
- OS: Ubuntu 18.04 and macOS Mojave

**Additional context**
Interestingly, it doesn't happen 100% of the time and I can not track down why it occasionally works as expected

Closed issue on VSCode: https://github.com/microsoft/vscode/issues/107403

**Comment by sobjornstad** [comment]
This is a major issue, editing is infuriating in this state if you move around by clicking even occasionally.

Until this is fixed, for anyone who isn't familiar, you can downgrade to 1.16.0 by right-clicking on the extension and choosing "Install Another Version". Downgrading has fixed the problem for me.

**Comment by berknam** [comment]
Can you please post your logs like explained [here](https://github.com/VSCodeVim/Vim#debugging-remappings)?

**Comment by berknam** [comment]
Can anyone here test PR #5250 to see if it fixes this issue and report back?

**Comment by mbochynski** [comment]
https://github.com/VSCodeVim/Vim/issues/5212 might be related? The issue for me is fixed in 1.17.1

**Comment by sobjornstad** [comment]
1.17.1 has fixed it for me as well.

**Comment by kalenpw** [comment]
I can also confirm 1.17.1 is working for me. Thanks for the quick fix!

**Comment by berknam** [comment]
@J-Fields version 1.17.1 fixed this only for click selection changes. Actually it just creates a workaround for them, but it doesn't actually fix the underlying issue. In PR #5250 I'm fixing one of the causes that I'm sure creates this issue. There might be others, I'm not sure yet. But it would be good to merge that PR so we could at least discard that reason.

Also, I think it is very important to deal with the situation I mentioned in this comment https://github.com/VSCodeVim/Vim/commit/523aca282cbb35bebe2493e1e43cb8c41083f110#r42752813

**Comment by bobbyhadz** [comment]
Still have this issue on Ubuntu, even with vim version 1.18.5, had to roll back the version to 1.16.0
