### ISSUE TITLE
When you click on a panel you're not focused on, the cursor position goes to the last cursor position rather than the location of the click.

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#896]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

**Comment by xconverge** [comment]
This was closed because it is a dupe of #794 not because it was fixed, correct?

**Comment by johnfn** [comment]
@xconverge It certainly appears to be fixed for me..?

**Comment by xconverge** [comment]
Working for me now...I haven't changed anything...probably a race condition...

**Comment by johnfn** [comment]
Amusingly, it just stopped working for me. 

Maybe I did some sort of condition in the code where it could only work for one contributor to VSCodeVim at a time?

**Comment by steinso** [comment]
I still have the same issue. For me it works correctly if it is the same file open in both panes, but not if it is two different files.
